ci: switch to makem.sh

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,8 +4,8 @@ on:
   pull_request:
   push:
     paths-ignore:
-    - '**/*.md'
-    - '**/*.org'
+      - "**/*.md"
+      - "**/*.org"
 
 jobs:
   build:
@@ -23,14 +23,27 @@ jobs:
           - 26.3
           - snapshot
     steps:
-    - uses: purcell/setup-emacs@master
-      with:
-        version: ${{ matrix.emacs_version }}
-    - uses: actions/setup-python@v2.1.4
-    - uses: conao3/setup-cask@master
+      - uses: purcell/setup-emacs@master
+        with:
+          version: ${{ matrix.emacs_version }}
 
-    - uses: actions/checkout@v2.3.4
-    - name: Install
-      run: cask install
-    - name: Test
-      run: cask exec buttercup -L .
+      - uses: actions/checkout@v2.3.4
+
+      - name: Create Sandbox Directory
+        run: |
+          SANDBOX_DIR=$(mktemp -d) || exit 1
+          echo "SANDBOX_DIR=$SANDBOX_DIR" >> $GITHUB_ENV
+
+      - name: Initialize Sandbox
+        run: |
+          ./makem.sh -vv --sandbox=$SANDBOX_DIR --install-deps --install-linters
+
+      # The "all" rule is not used, because it treats compilation warnings
+      # as failures, so linting and testing are run as separate steps.
+      - name: Lint
+        continue-on-error: true
+        run: ./makem.sh -vv --sandbox=$SANDBOX_DIR lint
+
+      - name: Test
+        if: always() # Run test even if linting fails.
+        run: ./makem.sh -vv --sandbox=$SANDBOX_DIR test
